export const tools = [
  {
    id: 1,
    name: "NextDocs AI",
    description: "AI-помощник для документации Next.js",
    longDescription: "Мощный AI-ассистент, специально обученный на официальной документации Next.js. Отвечает на вопросы, генерирует примеры кода и помогает решать проблемы.",
    category: "Код и разработка",
    logo: "https://placehold.co/64x64/8b5cf6/ffffff?text=ND",
    rating: 4.9,
    reviews: 342,
    views: 12500,
    likes: 890,
    added: "15 декабря 2025",
    link: "https://nextdocs.ai",
    tags: ["Next.js", "документация", "AI", "разработка"],
  },
  {
    id: 2,
    name: "Kling AI",
    description: "Генерация видео из текста и изображений",
    longDescription: "Передовая модель генерации видео от Kuaishou. Создаёт реалистичные видео до 2 минут по текстовому описанию или изображению.",
    category: "Видео & Анимация",
    logo: "https://placehold.co/64x64/ef4444/ffffff?text=KL",
    rating: 4.8,
    reviews: 567,
    views: 34200,
    likes: 2100,
    added: "10 декабря 2025",
    link: "https://kling.ai",
    tags: ["видео", "генерация", "текст-в-видео", "изображение-в-видео"],
  },
  {
    id: 3,
    name: "ForumScout",
    description: "AI-поиск по форумам и сообществам",
    longDescription: "Ищет ответы на форумах (Reddit, StackOverflow, Discord) с помощью AI. Находит реальные решения от пользователей.",
    category: "Продуктивность",
    logo: "https://placehold.co/64x64/10b981/ffffff?text=FS",
    rating: 4.7,
    reviews: 189,
    views: 8900,
    likes: 567,
    added: "12 декабря 2025",
    link: "https://forumscout.ai",
    tags: ["поиск", "форумы", "сообщества", "решение проблем"],
  },
  {
    id: 4,
    name: "Remio 2.0",
    description: "AI для создания интерактивных презентаций",
    longDescription: "Создаёт красивые интерактивные презентации с анимациями, видео и AI-генерацией контента по вашему описанию.",
    category: "Продуктивность",
    logo: "https://placehold.co/64x64/f59e0b/ffffff?text=RE",
    rating: 4.8,
    reviews: 412,
    views: 15600,
    likes: 1230,
    added: "14 декабря 2025",
    link: "https://remio.com",
    tags: ["презентации", "дизайн", "интерактив", "бизнес"],
  },
];